import Silk from "@/components/Silk/Silk";
import type { Metadata } from "next";
import { Montserrat_Alternates } from "next/font/google";
import "./globals.css";

const montserrat = Montserrat_Alternates({
  variable: "--font-montserrat",
  subsets: ["cyrillic", "latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Information Security Labs",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${montserrat.variable} antialiased`}>
        <div className="fixed inset-0 z-0">
          <Silk
            speed={5}
            scale={1}
            color="#14213D"
            noiseIntensity={1.5}
            rotation={0}
          />
        </div>
        <div className="relative z-10">{children}</div>
      </body>
    </html>
  );
}
